name: "Tests"
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
